sonar.projectKey=maersk_engineering-dashboard
sonar.sources=.
sonar.exclusions=**/*_test.go,**/testdata/**
sonar.coverage.exclusions=**/*_test.go,**/testdata/**
sonar.cpd.exclusions=**/*_test.go,**/testdata/**
